sudo: required
services:
  - docker
before_install:
  - docker build -t hadeces/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hadeces/react-test npm test

after_success:
  - docker build -t hadeces/multi-client ./client
  - docker build -t hadeces/multi-nginx ./nginx
  - docker build -t hadeces/multi-server ./server
  - docker build -t hadeces/multi-worker ./worker
