sudo: required
services:
  - docker
before_install:
  - docker build -t hadeces/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hadeces/react-test npm test

after_success:
  - docker build -t hadeces/multi-client ./client
  - docker build -t hadeces/multi-nginx ./nginx
  - docker build -t hadeces/multi-server ./server
  - docker build -t hadeces/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push hadeces/multi-client
  - docker push hadeces/multi-nginx
  - docker push hadeces/multi-server
  - docker push hadeces/multi-worker
deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-561374553667'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY