version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgrespassword
  redis:
    image: 'redis:4-alpine'
  api:
    build:
      dockerfile: 'Dockerfile.dev'
      context: './server'
    restart: always
    volumes:
      #      "COPY"(reference) All except node_modules folder
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      # Services referenced upon
      - PGHOST=postgres
      - PGDATABASE=fibvalues
      - PGPASSWORD=postgrespassword
      - PGPORT=5432
    depends_on:
      - redis
      - postgres
  client:
    build:
      dockerfile: 'Dockerfile.dev'
      context: './client'
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0

  worker:
    build:
      dockerfile: 'Dockerfile.dev'
      context: './worker'
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - postgres
  nginx:
    restart: always
    build:
      dockerfile: 'Dockerfile.dev'
      context: './nginx'
    ports:
      - '3050:80'
    depends_on:
      - api
      - client
      - worker